#!/usr/bin/env ruby

require 'rubygems'        # if you use RubyGems
require 'daemons'
require 'fileutils'

ARGV.push("--").push("--log").push(File.expand_path( File.dirname(__FILE__)  + "/../log/development.log")).push("-e").push("production")

Daemons.run(File.join(File.dirname(__FILE__),  '../json_proxy.rb'),   
            :dir_mode => :script, 
            :dir => "log",
            :mode => "exec")

