#!/usr/bin/env ruby

require 'rubygems'        # if you use RubyGems
require 'daemons'

ARGV.push("--").push("--log").push(File.expand_path( File.dirname(__FILE__)  + "/../log/development.log"))

Daemons.run(File.join(File.dirname(__FILE__),  '../nowplaying.rb'),   
            :dir_mode => :script, 
            :dir => "log")

